name: Build Windows EXE Fast

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release Fast
      run: cargo build --release

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hanteker-GUI-Windows
        path: target/release/hanteker_gui.exe
