name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install vcpkg and dependencies
      run: |
        vcpkg integrate install
        vcpkg install skia:x64-windows

    - name: Build Release
      run: cargo build --release
      env:
        SLINT_BACKEND: skia

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hanteker-GUI-Windows
        path: target/release/hanteker_gui.exe
